CREATE TABLE EventsArchive LIKE Events;

CREATE EVENT evt_ArchiveEvents
ON SCHEDULE EVERY 1 DAY
STARTS CURRENT_TIMESTAMP + INTERVAL (24 - HOUR(CURRENT_TIMESTAMP) + 3) HOUR
DO
    CALL sp_ArchiveOldEvents();